[global]
developmentMode = false
showWarningOnDirectExecution = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 10
port = 8501
address = "0.0.0.0"
baseUrlPath = ""
maxMessageSize = 200

# Disable health checks to prevent timeout issues during model loading
scriptHealthCheckEnabled = false

# Additional performance settings
fileWatcherType = "auto"
allowRunOnSave = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F5"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s" 